version: '3.9'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - idea-service
      - vote-service
      - comment-service
      - auth-service
    networks: [app]
  idea-service:
    build: ./services/idea-service
    env_file: .env
    networks: [app]
    depends_on:
      - db
      - rabbitmq
  vote-service:
    build: ./services/vote-service
    env_file: .env
    networks: [app]
    depends_on:
      - db
      - rabbitmq
  comment-service:
    build: ./services/comment-service
    env_file: .env
    networks: [app]
    depends_on:
      - db
      - rabbitmq
  auth-service:
    build: ./services/auth-service
    env_file: .env
    networks: [app]
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file: .env
    networks: [app]
    depends_on:
      - gateway
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ideas
      POSTGRES_PASSWORD: ideas
      POSTGRES_DB: ideas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    networks: [app]
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks: [app]
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [app]
networks:
  app: {}
volumes:
  db_data: {}
